<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="12" passed="1" failed="11" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-06-23T15:17:46 EET" name="Suite" finished-at="2022-06-23T15:20:56 EET" duration-ms="190351">
    <groups>
    </groups>
    <test started-at="2022-06-23T15:17:46 EET" name="Test" finished-at="2022-06-23T15:20:56 EET" duration-ms="190351">
      <class name="Pages.ReportWaffarAd">
        <test-method is-config="true" signature="start()[pri:0, instance:Pages.ReportWaffarAd@34a3d150]" started-at="2022-06-23T15:17:46 EET" name="start" finished-at="2022-06-23T15:17:46 EET" duration-ms="238" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- start -->
        <test-method is-config="true" signature="End()[pri:0, instance:Pages.ReportWaffarAd@34a3d150]" started-at="2022-06-23T15:20:57 EET" name="End" finished-at="2022-06-23T15:20:57 EET" duration-ms="437" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- End -->
      </class> <!-- Pages.ReportWaffarAd -->
      <class name="Pages.EditOrder_In_Yashry">
        <test-method is-config="true" signature="open_URL()[pri:0, instance:Pages.EditOrder_In_Yashry@57a3af25]" started-at="2022-06-23T15:17:46 EET" name="open_URL" finished-at="2022-06-23T15:18:04 EET" duration-ms="18184" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- open_URL -->
        <test-method signature="CheckThat_someFields_Disabled()[pri:0, instance:Pages.EditOrder_In_Yashry@57a3af25]" started-at="2022-06-23T15:18:04 EET" name="CheckThat_someFields_Disabled" finished-at="2022-06-23T15:18:05 EET" duration-ms="230" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CheckThat_someFields_Disabled -->
        <test-method is-config="true" signature="quit(org.testng.ITestResult)[pri:0, instance:Pages.EditOrder_In_Yashry@57a3af25]" started-at="2022-06-23T15:18:05 EET" name="quit" finished-at="2022-06-23T15:18:05 EET" duration-ms="299" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=CheckThat_someFields_Disabled status=SUCCESS method=EditOrder_In_Yashry.CheckThat_someFields_Disabled()[pri:0, instance:Pages.EditOrder_In_Yashry@57a3af25] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
        <test-method is-config="true" signature="open_URL()[pri:0, instance:Pages.EditOrder_In_Yashry@57a3af25]" started-at="2022-06-23T15:18:05 EET" name="open_URL" finished-at="2022-06-23T15:18:18 EET" duration-ms="13447" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- open_URL -->
        <test-method signature="ValidData_WithInsert_NegativeNumber_In_OrderDiscount()[pri:0, instance:Pages.EditOrder_In_Yashry@57a3af25]" started-at="2022-06-23T15:18:18 EET" name="ValidData_WithInsert_NegativeNumber_In_OrderDiscount" finished-at="2022-06-23T15:18:18 EET" duration-ms="155" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [713982] but found [714688]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [713982] but found [714688]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at Pages.EditOrder_In_Yashry.ValidData_WithInsert_NegativeNumber_In_OrderDiscount(EditOrder_In_Yashry.java:392)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidData_WithInsert_NegativeNumber_In_OrderDiscount -->
        <test-method is-config="true" signature="quit(org.testng.ITestResult)[pri:0, instance:Pages.EditOrder_In_Yashry@57a3af25]" started-at="2022-06-23T15:18:18 EET" name="quit" finished-at="2022-06-23T15:18:19 EET" duration-ms="380" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=ValidData_WithInsert_NegativeNumber_In_OrderDiscount status=FAILURE method=EditOrder_In_Yashry.ValidData_WithInsert_NegativeNumber_In_OrderDiscount()[pri:0, instance:Pages.EditOrder_In_Yashry@57a3af25] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
        <test-method is-config="true" signature="open_URL()[pri:0, instance:Pages.EditOrder_In_Yashry@57a3af25]" started-at="2022-06-23T15:18:19 EET" name="open_URL" finished-at="2022-06-23T15:18:35 EET" duration-ms="15876" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- open_URL -->
        <test-method signature="ValidData_WithInsert_NegativeNumber_In_OrderShipping()[pri:0, instance:Pages.EditOrder_In_Yashry@57a3af25]" started-at="2022-06-23T15:18:35 EET" name="ValidData_WithInsert_NegativeNumber_In_OrderShipping" finished-at="2022-06-23T15:18:35 EET" duration-ms="42" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [713982] but found [714688]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [713982] but found [714688]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at Pages.EditOrder_In_Yashry.ValidData_WithInsert_NegativeNumber_In_OrderShipping(EditOrder_In_Yashry.java:223)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidData_WithInsert_NegativeNumber_In_OrderShipping -->
        <test-method is-config="true" signature="quit(org.testng.ITestResult)[pri:0, instance:Pages.EditOrder_In_Yashry@57a3af25]" started-at="2022-06-23T15:18:35 EET" name="quit" finished-at="2022-06-23T15:18:39 EET" duration-ms="4442" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=ValidData_WithInsert_NegativeNumber_In_OrderShipping status=FAILURE method=EditOrder_In_Yashry.ValidData_WithInsert_NegativeNumber_In_OrderShipping()[pri:0, instance:Pages.EditOrder_In_Yashry@57a3af25] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
        <test-method is-config="true" signature="open_URL()[pri:0, instance:Pages.EditOrder_In_Yashry@57a3af25]" started-at="2022-06-23T15:18:39 EET" name="open_URL" finished-at="2022-06-23T15:18:53 EET" duration-ms="13820" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- open_URL -->
        <test-method signature="ValidData_WithInsert_NegativeNumber_In_OrderTotal()[pri:0, instance:Pages.EditOrder_In_Yashry@57a3af25]" started-at="2022-06-23T15:18:53 EET" name="ValidData_WithInsert_NegativeNumber_In_OrderTotal" finished-at="2022-06-23T15:18:53 EET" duration-ms="41" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [713982] but found [714688]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [713982] but found [714688]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at Pages.EditOrder_In_Yashry.ValidData_WithInsert_NegativeNumber_In_OrderTotal(EditOrder_In_Yashry.java:96)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidData_WithInsert_NegativeNumber_In_OrderTotal -->
        <test-method is-config="true" signature="quit(org.testng.ITestResult)[pri:0, instance:Pages.EditOrder_In_Yashry@57a3af25]" started-at="2022-06-23T15:18:53 EET" name="quit" finished-at="2022-06-23T15:18:53 EET" duration-ms="296" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=ValidData_WithInsert_NegativeNumber_In_OrderTotal status=FAILURE method=EditOrder_In_Yashry.ValidData_WithInsert_NegativeNumber_In_OrderTotal()[pri:0, instance:Pages.EditOrder_In_Yashry@57a3af25] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
        <test-method is-config="true" signature="open_URL()[pri:0, instance:Pages.EditOrder_In_Yashry@57a3af25]" started-at="2022-06-23T15:18:53 EET" name="open_URL" finished-at="2022-06-23T15:19:09 EET" duration-ms="15358" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- open_URL -->
        <test-method signature="ValidData_WithInsert_OrderDiscount_GreaterThan_OrderTotal()[pri:0, instance:Pages.EditOrder_In_Yashry@57a3af25]" started-at="2022-06-23T15:19:09 EET" name="ValidData_WithInsert_OrderDiscount_GreaterThan_OrderTotal" finished-at="2022-06-23T15:19:09 EET" duration-ms="53" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [713982] but found [714688]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [713982] but found [714688]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at Pages.EditOrder_In_Yashry.ValidData_WithInsert_OrderDiscount_GreaterThan_OrderTotal(EditOrder_In_Yashry.java:518)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidData_WithInsert_OrderDiscount_GreaterThan_OrderTotal -->
        <test-method is-config="true" signature="quit(org.testng.ITestResult)[pri:0, instance:Pages.EditOrder_In_Yashry@57a3af25]" started-at="2022-06-23T15:19:09 EET" name="quit" finished-at="2022-06-23T15:19:13 EET" duration-ms="4319" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=ValidData_WithInsert_OrderDiscount_GreaterThan_OrderTotal status=FAILURE method=EditOrder_In_Yashry.ValidData_WithInsert_OrderDiscount_GreaterThan_OrderTotal()[pri:0, instance:Pages.EditOrder_In_Yashry@57a3af25] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
        <test-method is-config="true" signature="open_URL()[pri:0, instance:Pages.EditOrder_In_Yashry@57a3af25]" started-at="2022-06-23T15:19:13 EET" name="open_URL" finished-at="2022-06-23T15:19:28 EET" duration-ms="14635" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- open_URL -->
        <test-method signature="ValidData_WithInsert_OrderShipping_GreaterThan_OrderTotal()[pri:0, instance:Pages.EditOrder_In_Yashry@57a3af25]" started-at="2022-06-23T15:19:28 EET" name="ValidData_WithInsert_OrderShipping_GreaterThan_OrderTotal" finished-at="2022-06-23T15:19:28 EET" duration-ms="46" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [713982] but found [714688]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [713982] but found [714688]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at Pages.EditOrder_In_Yashry.ValidData_WithInsert_OrderShipping_GreaterThan_OrderTotal(EditOrder_In_Yashry.java:349)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidData_WithInsert_OrderShipping_GreaterThan_OrderTotal -->
        <test-method is-config="true" signature="quit(org.testng.ITestResult)[pri:0, instance:Pages.EditOrder_In_Yashry@57a3af25]" started-at="2022-06-23T15:19:28 EET" name="quit" finished-at="2022-06-23T15:19:28 EET" duration-ms="285" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=ValidData_WithInsert_OrderShipping_GreaterThan_OrderTotal status=FAILURE method=EditOrder_In_Yashry.ValidData_WithInsert_OrderShipping_GreaterThan_OrderTotal()[pri:0, instance:Pages.EditOrder_In_Yashry@57a3af25] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
        <test-method is-config="true" signature="open_URL()[pri:0, instance:Pages.EditOrder_In_Yashry@57a3af25]" started-at="2022-06-23T15:19:28 EET" name="open_URL" finished-at="2022-06-23T15:19:42 EET" duration-ms="14091" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- open_URL -->
        <test-method signature="ValidData_With_Insert_Zero_In_OrderDiscount()[pri:0, instance:Pages.EditOrder_In_Yashry@57a3af25]" started-at="2022-06-23T15:19:42 EET" name="ValidData_With_Insert_Zero_In_OrderDiscount" finished-at="2022-06-23T15:19:42 EET" duration-ms="40" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [713982] but found [714688]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [713982] but found [714688]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at Pages.EditOrder_In_Yashry.ValidData_With_Insert_Zero_In_OrderDiscount(EditOrder_In_Yashry.java:476)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidData_With_Insert_Zero_In_OrderDiscount -->
        <test-method is-config="true" signature="quit(org.testng.ITestResult)[pri:0, instance:Pages.EditOrder_In_Yashry@57a3af25]" started-at="2022-06-23T15:19:42 EET" name="quit" finished-at="2022-06-23T15:19:42 EET" duration-ms="188" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=ValidData_With_Insert_Zero_In_OrderDiscount status=FAILURE method=EditOrder_In_Yashry.ValidData_With_Insert_Zero_In_OrderDiscount()[pri:0, instance:Pages.EditOrder_In_Yashry@57a3af25] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
        <test-method is-config="true" signature="open_URL()[pri:0, instance:Pages.EditOrder_In_Yashry@57a3af25]" started-at="2022-06-23T15:19:42 EET" name="open_URL" finished-at="2022-06-23T15:19:57 EET" duration-ms="14722" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- open_URL -->
        <test-method signature="ValidData_With_Insert_Zero_In_OrderShipping()[pri:0, instance:Pages.EditOrder_In_Yashry@57a3af25]" started-at="2022-06-23T15:19:57 EET" name="ValidData_With_Insert_Zero_In_OrderShipping" finished-at="2022-06-23T15:19:57 EET" duration-ms="39" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [713982] but found [714688]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [713982] but found [714688]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at Pages.EditOrder_In_Yashry.ValidData_With_Insert_Zero_In_OrderShipping(EditOrder_In_Yashry.java:307)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidData_With_Insert_Zero_In_OrderShipping -->
        <test-method is-config="true" signature="quit(org.testng.ITestResult)[pri:0, instance:Pages.EditOrder_In_Yashry@57a3af25]" started-at="2022-06-23T15:19:57 EET" name="quit" finished-at="2022-06-23T15:19:57 EET" duration-ms="259" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=ValidData_With_Insert_Zero_In_OrderShipping status=FAILURE method=EditOrder_In_Yashry.ValidData_With_Insert_Zero_In_OrderShipping()[pri:0, instance:Pages.EditOrder_In_Yashry@57a3af25] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
        <test-method is-config="true" signature="open_URL()[pri:0, instance:Pages.EditOrder_In_Yashry@57a3af25]" started-at="2022-06-23T15:19:57 EET" name="open_URL" finished-at="2022-06-23T15:20:11 EET" duration-ms="13757" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- open_URL -->
        <test-method signature="ValidData_With_Insert_Zero_In_OrderTotal()[pri:0, instance:Pages.EditOrder_In_Yashry@57a3af25]" started-at="2022-06-23T15:20:11 EET" name="ValidData_With_Insert_Zero_In_OrderTotal" finished-at="2022-06-23T15:20:11 EET" duration-ms="122" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [713982] but found [714688]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [713982] but found [714688]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at Pages.EditOrder_In_Yashry.ValidData_With_Insert_Zero_In_OrderTotal(EditOrder_In_Yashry.java:180)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidData_With_Insert_Zero_In_OrderTotal -->
        <test-method is-config="true" signature="quit(org.testng.ITestResult)[pri:0, instance:Pages.EditOrder_In_Yashry@57a3af25]" started-at="2022-06-23T15:20:11 EET" name="quit" finished-at="2022-06-23T15:20:12 EET" duration-ms="534" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=ValidData_With_Insert_Zero_In_OrderTotal status=FAILURE method=EditOrder_In_Yashry.ValidData_With_Insert_Zero_In_OrderTotal()[pri:0, instance:Pages.EditOrder_In_Yashry@57a3af25] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
        <test-method is-config="true" signature="open_URL()[pri:0, instance:Pages.EditOrder_In_Yashry@57a3af25]" started-at="2022-06-23T15:20:12 EET" name="open_URL" finished-at="2022-06-23T15:20:26 EET" duration-ms="14606" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- open_URL -->
        <test-method signature="ValidData_Without_InsertData_In_OrderDiscount()[pri:0, instance:Pages.EditOrder_In_Yashry@57a3af25]" started-at="2022-06-23T15:20:26 EET" name="ValidData_Without_InsertData_In_OrderDiscount" finished-at="2022-06-23T15:20:27 EET" duration-ms="65" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [713982] but found [714688]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [713982] but found [714688]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at Pages.EditOrder_In_Yashry.ValidData_Without_InsertData_In_OrderDiscount(EditOrder_In_Yashry.java:434)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidData_Without_InsertData_In_OrderDiscount -->
        <test-method is-config="true" signature="quit(org.testng.ITestResult)[pri:0, instance:Pages.EditOrder_In_Yashry@57a3af25]" started-at="2022-06-23T15:20:27 EET" name="quit" finished-at="2022-06-23T15:20:27 EET" duration-ms="372" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=ValidData_Without_InsertData_In_OrderDiscount status=FAILURE method=EditOrder_In_Yashry.ValidData_Without_InsertData_In_OrderDiscount()[pri:0, instance:Pages.EditOrder_In_Yashry@57a3af25] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
        <test-method is-config="true" signature="open_URL()[pri:0, instance:Pages.EditOrder_In_Yashry@57a3af25]" started-at="2022-06-23T15:20:27 EET" name="open_URL" finished-at="2022-06-23T15:20:42 EET" duration-ms="15140" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- open_URL -->
        <test-method signature="ValidData_Without_InsertData_In_OrderShipping()[pri:0, instance:Pages.EditOrder_In_Yashry@57a3af25]" started-at="2022-06-23T15:20:42 EET" name="ValidData_Without_InsertData_In_OrderShipping" finished-at="2022-06-23T15:20:42 EET" duration-ms="70" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [713982] but found [714688]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [713982] but found [714688]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at Pages.EditOrder_In_Yashry.ValidData_Without_InsertData_In_OrderShipping(EditOrder_In_Yashry.java:265)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidData_Without_InsertData_In_OrderShipping -->
        <test-method is-config="true" signature="quit(org.testng.ITestResult)[pri:0, instance:Pages.EditOrder_In_Yashry@57a3af25]" started-at="2022-06-23T15:20:42 EET" name="quit" finished-at="2022-06-23T15:20:43 EET" duration-ms="430" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=ValidData_Without_InsertData_In_OrderShipping status=FAILURE method=EditOrder_In_Yashry.ValidData_Without_InsertData_In_OrderShipping()[pri:0, instance:Pages.EditOrder_In_Yashry@57a3af25] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
        <test-method is-config="true" signature="open_URL()[pri:0, instance:Pages.EditOrder_In_Yashry@57a3af25]" started-at="2022-06-23T15:20:43 EET" name="open_URL" finished-at="2022-06-23T15:20:56 EET" duration-ms="13711" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- open_URL -->
        <test-method signature="ValidData_Without_InsertData_In_OrderTotal()[pri:0, instance:Pages.EditOrder_In_Yashry@57a3af25]" started-at="2022-06-23T15:20:56 EET" name="ValidData_Without_InsertData_In_OrderTotal" finished-at="2022-06-23T15:20:56 EET" duration-ms="34" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [713982] but found [714688]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [713982] but found [714688]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at Pages.EditOrder_In_Yashry.ValidData_Without_InsertData_In_OrderTotal(EditOrder_In_Yashry.java:138)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidData_Without_InsertData_In_OrderTotal -->
        <test-method is-config="true" signature="quit(org.testng.ITestResult)[pri:0, instance:Pages.EditOrder_In_Yashry@57a3af25]" started-at="2022-06-23T15:20:56 EET" name="quit" finished-at="2022-06-23T15:20:56 EET" duration-ms="179" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=ValidData_Without_InsertData_In_OrderTotal status=FAILURE method=EditOrder_In_Yashry.ValidData_Without_InsertData_In_OrderTotal()[pri:0, instance:Pages.EditOrder_In_Yashry@57a3af25] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- Pages.EditOrder_In_Yashry -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
